In [1]:
import numpy as np

In [ ]:
np.arange(start,stop,step) #also support fraction or decimal

In [2]:
np.arange(1,10,2.5)

array([1. , 3.5, 6. , 8.5])

In [ ]:
# #reshape

# [1,2,3,4] 1X4 matrix ---->  [1 2
#                              3  4] this is a 2X2 matrix 

# OR


# [1,2,3,4] 1X4 matrix ----> [ - - -
#                              -  - -
#                              - - -]   this is a 3x3 matrix with 9 elements



# no. of elemnsts = a1Xa2Xa3  - reshaping of number of elemnts inside an array can be done only in some few ways only right.





In [3]:
n1 =np.arange(1,5)
n1 #this array has 4 elements 
# so the way this array can be arranged is either in 2X2 ways 


array([1, 2, 3, 4])

In [6]:
n1.shape #its a one d array

(4,)

In [7]:
m1 =n1.reshape(2,2) 
m1

array([[1, 2],
       [3, 4]])

In [9]:
m1.shape # 2-d array

(2, 2)

In [10]:
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
np.arange(1,10).reshape(4,3) #4*3 =12 (but here we have only 9 elements)
#i dont have 12 things to fill in

ValueError: cannot reshape array of size 9 into shape (4,3)

In [13]:
np.arange(1,10).reshape(2,3) #have less elements where will the rest of the elemnst to go.
#6 spaces hai lekin 9 elemts fill karne hai.

ValueError: cannot reshape array of size 9 into shape (2,3)

In [15]:
np.arange(1,9).reshape(2,4) # 1,2,3,4,5,6,7,8

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [17]:
np.arange(1,9).reshape(2,2,2) #1-9 has 8 elements and 2X2X2  = 8
# two 2x2 matrices are there 

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [18]:
np.arange(1,17).reshape(8,2) # 16 elements = 8X2

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16]])

In [19]:
np.arange(1,17).reshape(1,16)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16]])

In [20]:
np.arange(1,17).reshape(4,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [21]:
np.arange(1,17).reshape(2,4,2) # Two 4x2 matrices

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12],
        [13, 14],
        [15, 16]]])

In [22]:
np.arange(1,17).reshape(16,1) #16 elements araanged in 16X1 matrix type

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16]])

In [23]:
np.arange(1,17).reshape(2,2,2,2) # 2x2x2x2

# two 2x2x2 3-d arrays

array([[[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]]],


       [[[ 9, 10],
         [11, 12]],

        [[13, 14],
         [15, 16]]]])

In [24]:
np.arange(1,5).reshape(2,2,1,1,1,1,1,1,1,1,1)

array([[[[[[[[[[[1]]]]]]]]],








        [[[[[[[[[2]]]]]]]]]],









       [[[[[[[[[[3]]]]]]]]],








        [[[[[[[[[4]]]]]]]]]]])