## np.arange()

In [ ]:
import numpy as np
np.arange(start,stop,step) #also support fraction or decimal

In [2]:
np.arange(1,10,2.5)

array([1. , 3.5, 6. , 8.5])

In [ ]:
# #reshape

# [1,2,3,4] 1X4 matrix ---->  [1 2
#                              3  4] this is a 2X2 matrix 

# OR


# [1,2,3,4] 1X4 matrix ----> [ - - -
#                              -  - -
#                              - - -]   this is a 3x3 matrix with 9 elements



# no. of elemnsts = a1Xa2Xa3  - reshaping of number of elemnts inside an array can be done only in some few ways only right.





In [3]:
n1 =np.arange(1,5)
n1 #this array has 4 elements 
# so the way this array can be arranged is either in 2X2 ways 


array([1, 2, 3, 4])

In [6]:
n1.shape #its a one d array

(4,)

In [7]:
m1 =n1.reshape(2,2) 
m1

array([[1, 2],
       [3, 4]])

In [9]:
m1.shape # 2-d array

(2, 2)

In [10]:
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
np.arange(1,10).reshape(4,3) #4*3 =12 (but here we have only 9 elements)
#i dont have 12 things to fill in

ValueError: cannot reshape array of size 9 into shape (4,3)

In [13]:
np.arange(1,10).reshape(2,3) #have less elements where will the rest of the elemnst to go.
#6 spaces hai lekin 9 elemts fill karne hai.

ValueError: cannot reshape array of size 9 into shape (2,3)

In [15]:
np.arange(1,9).reshape(2,4) # 1,2,3,4,5,6,7,8

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [17]:
np.arange(1,9).reshape(2,2,2) #1-9 has 8 elements and 2X2X2  = 8
# two 2x2 matrices are there 

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [18]:
np.arange(1,17).reshape(8,2) # 16 elements = 8X2

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16]])

In [19]:
np.arange(1,17).reshape(1,16)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16]])

In [20]:
np.arange(1,17).reshape(4,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [21]:
np.arange(1,17).reshape(2,4,2) # Two 4x2 matrices

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12],
        [13, 14],
        [15, 16]]])

In [22]:
np.arange(1,17).reshape(16,1) #16 elements araanged in 16X1 matrix type

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16]])

In [23]:
np.arange(1,17).reshape(2,2,2,2) # 2x2x2x2

# two 2x2x2 3-d arrays

array([[[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]]],


       [[[ 9, 10],
         [11, 12]],

        [[13, 14],
         [15, 16]]]])

In [24]:
np.arange(1,5).reshape(2,2,1,1,1,1,1,1,1,1,1)

array([[[[[[[[[[[1]]]]]]]]],








        [[[[[[[[[2]]]]]]]]]],









       [[[[[[[[[[3]]]]]]]]],








        [[[[[[[[[4]]]]]]]]]]])

In [26]:
np.arange(1,9).reshape(2,2,2).shape

(2, 2, 2)

In [28]:
np.arange(0,12).reshape(2,2,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

# np.zeros and np.ones and np.identity and np.eye

## all have zeros  and all have ones  , gives a identity matrix, (can give diff rows and columns just make sure that diagonal elements are 1.)

In [29]:
(5,) #tuple of single element

(5,)

In [31]:
np.zeros(5) #np.zeros excepts either an int or a tuple

array([0., 0., 0., 0., 0.])

In [33]:
np.zeros((5,),dtype=int)

array([0, 0, 0, 0, 0])

In [35]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [39]:
np.zeros([4,4],dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [40]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [41]:
np.ones((4,4),dtype=str)

array([['1', '1', '1', '1'],
       ['1', '1', '1', '1'],
       ['1', '1', '1', '1'],
       ['1', '1', '1', '1']], dtype='<U1')

In [42]:
np.ones((2,))

array([1., 1.])

In [43]:
np.identity(3) #square matrix - rows = columns
#by default it would create a 2-d array as its is a matrix(meaning 2-d array only na)

# identity matrix has all the diagnoal elements as 1. 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# np.eye is an extension of identity matrix, just that it necessarily not be a square matric , it can be a non squre matrix too , its jsut that it makes the diagonal elemets as 1 and rest as 0.

In [45]:
np.eye(4,2) #4-rows and 2 columns 

#rows and columns are different - need not be square matrix - its just make sures that everything in the diagonal matrix is 1.

array([[1., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.]])

In [46]:
np.eye(3) #creates a square matrix only

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [50]:
#can give rows and columns also
np.eye(2,3) 

array([[1., 0., 0.],
       [0., 1., 0.]])

In [52]:
np.eye(5,M= 6) #5 rows and 6 colums

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.]])