# DIFFERENT WAYS TO CREATE NUMPY ARRAYS:

1. np.arange()
2. np.zeros()
3. np.ones()
4. np.eye()
5. np.random()
6. np.linspace()
7. np.min()
8. np.max()
9. np.ravel() #har ek element print ho jayega
10. np.nditer  # np.ravel() and np.nditer are same thing
11. reshape
12. shape
13. size
14. astype
15. indexing,   slicing, operations.


## np.arange()

In [ ]:
import numpy as np
np.arange(start,stop,step) #also support fraction or decimal

In [2]:
np.arange(1,10,2.5)

array([1. , 3.5, 6. , 8.5])

In [ ]:
# #reshape

# [1,2,3,4] 1X4 matrix ---->  [1 2
#                              3  4] this is a 2X2 matrix 

# OR


# [1,2,3,4] 1X4 matrix ----> [ - - -
#                              -  - -
#                              - - -]   this is a 3x3 matrix with 9 elements



# no. of elemnsts = a1Xa2Xa3  - reshaping of number of elemnts inside an array can be done only in some few ways only right.





In [3]:
n1 =np.arange(1,5)
n1 #this array has 4 elements 
# so the way this array can be arranged is either in 2X2 ways 


array([1, 2, 3, 4])

In [6]:
n1.shape #its a one d array

(4,)

In [7]:
m1 =n1.reshape(2,2) 
m1

array([[1, 2],
       [3, 4]])

In [9]:
m1.shape # 2-d array

(2, 2)

In [10]:
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
np.arange(1,10).reshape(4,3) #4*3 =12 (but here we have only 9 elements)
#i dont have 12 things to fill in

ValueError: cannot reshape array of size 9 into shape (4,3)

In [13]:
np.arange(1,10).reshape(2,3) #have less elements where will the rest of the elemnst to go.
#6 spaces hai lekin 9 elemts fill karne hai.

ValueError: cannot reshape array of size 9 into shape (2,3)

In [15]:
np.arange(1,9).reshape(2,4) # 1,2,3,4,5,6,7,8

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [17]:
np.arange(1,9).reshape(2,2,2) #1-9 has 8 elements and 2X2X2  = 8
# two 2x2 matrices are there 

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [18]:
np.arange(1,17).reshape(8,2) # 16 elements = 8X2

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16]])

In [19]:
np.arange(1,17).reshape(1,16)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16]])

In [20]:
np.arange(1,17).reshape(4,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [21]:
np.arange(1,17).reshape(2,4,2) # Two 4x2 matrices

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12],
        [13, 14],
        [15, 16]]])

In [22]:
np.arange(1,17).reshape(16,1) #16 elements araanged in 16X1 matrix type

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16]])

In [23]:
np.arange(1,17).reshape(2,2,2,2) # 2x2x2x2

# two 2x2x2 3-d arrays

array([[[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]]],


       [[[ 9, 10],
         [11, 12]],

        [[13, 14],
         [15, 16]]]])

In [24]:
np.arange(1,5).reshape(2,2,1,1,1,1,1,1,1,1,1)

array([[[[[[[[[[[1]]]]]]]]],








        [[[[[[[[[2]]]]]]]]]],









       [[[[[[[[[[3]]]]]]]]],








        [[[[[[[[[4]]]]]]]]]]])

In [26]:
np.arange(1,9).reshape(2,2,2).shape

(2, 2, 2)

In [28]:
np.arange(0,12).reshape(2,2,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

# np.zeros and np.ones and np.identity and np.eye

## all have zeros  and all have ones  , gives a identity matrix, (can give diff rows and columns just make sure that diagonal elements are 1.)

In [29]:
(5,) #tuple of single element

(5,)

In [31]:
np.zeros(5) #np.zeros excepts either an int or a tuple

array([0., 0., 0., 0., 0.])

In [33]:
np.zeros((5,),dtype=int)

array([0, 0, 0, 0, 0])

In [35]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [39]:
np.zeros([4,4],dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [40]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [41]:
np.ones((4,4),dtype=str)

array([['1', '1', '1', '1'],
       ['1', '1', '1', '1'],
       ['1', '1', '1', '1'],
       ['1', '1', '1', '1']], dtype='<U1')

In [42]:
np.ones((2,))

array([1., 1.])

In [43]:
np.identity(3) #square matrix - rows = columns
#by default it would create a 2-d array as its is a matrix(meaning 2-d array only na)

# identity matrix has all the diagnoal elements as 1. 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# np.eye is an extension of identity matrix, just that it necessarily not be a square matric , it can be a non squre matrix too , its jsut that it makes the diagonal elemets as 1 and rest as 0.

In [45]:
np.eye(4,2) #4-rows and 2 columns 

#rows and columns are different - need not be square matrix - its just make sures that everything in the diagonal matrix is 1.

array([[1., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.]])

In [55]:
np.eye(3) #creates a square matrix only
# 3 is the number of rows in the input
# and M- which is the number of columns is optional in input

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [50]:
#can give rows and columns also
np.eye(2,3) 

array([[1., 0., 0.],
       [0., 1., 0.]])

In [52]:
np.eye(5,M= 6) #5 rows and 6 colums

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.]])

# np.random

## gives random numbes from 0 to 1

In [53]:
np.random.random(5) #one dimensional coz one argument is passed

array([0.77732077, 0.97207831, 0.04328164, 0.73873589, 0.55850794])

In [58]:
np.random.random((3,4)) # number of rows * number of cols
#tuple is passed

array([[0.18100464, 0.78466805, 0.36899072, 0.39375325],
       [0.48344982, 0.9948834 , 0.81658012, 0.86520157],
       [0.6136897 , 0.22792082, 0.2701558 , 0.00462853]])

In [59]:
np.random.random((5,5))

array([[0.34637769, 0.12339307, 0.63683636, 0.08909565, 0.59285882],
       [0.91449008, 0.86905928, 0.71224824, 0.26037216, 0.75510429],
       [0.1134573 , 0.25638669, 0.66136378, 0.45948569, 0.56545199],
       [0.35455366, 0.18516473, 0.40666963, 0.59948161, 0.14653984],
       [0.84009602, 0.77783633, 0.68875074, 0.75729973, 0.57310334]])

In [60]:
# can we set it to random range

In [61]:
np.random.random((4,4))*100

array([[58.93942421,  9.36179515, 87.16690761,  1.48081374],
       [57.88622888, 83.96574438, 50.87801641, 25.63826932],
       [38.21636237, 33.06945722, 92.08138377, 74.98502143],
       [92.56992141, 19.22797472, 75.72002849, 80.61735795]])

In [62]:
np.random.randint(1,5) # is range ke beech mein koi bhi random integer

4

In [63]:
np.random.randint(8,10)

8

In [64]:
np.random.randint(1,10,size = (2,2)) #random intger of this 2x2 size

array([[4, 5],
       [4, 3]])

In [65]:
np.random.randint(1,100,size = (2,3))

array([[90, 23, 49],
       [68, 73, 47]])

In [66]:
import math
math.factorial(4)

24

In [68]:
list(range(6))

[0, 1, 2, 3, 4, 5]

In [77]:
list(range(1,6))

[1, 2, 3, 4, 5]

In [83]:
a =1
for i in list(range(1,6)):
    print(i,a)
    a = a*i
   

1 1
2 1
3 2
4 6
5 24


In [82]:
a

120

In [84]:
list(range(1,6)) # need to find 5! factorial

[1, 2, 3, 4, 5]

In [85]:
ans= 1

for i in range(1,6):

    ans = ans *i

In [86]:
ans

120

# np.linspace

# np.linspace

## used for plotting graphs as graph is qually spaced. 

## spacing =        end- start
              --------------------------------       
##             total_jitne_numbers_banan_hai -1 

In [92]:
# np.linspace(start,stop,number) #means how many numbers we want
# gives number in the range [start,stop]

#by default everything in numpy as float as we want to preserve the information

In [90]:
np.linspace(0,10,6) #i need 6 numbers between the range of [0,10] # 0 and 10 are inclusive

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [93]:
np.linspace(0,10,num=4)

#numbers are equally spcaed between each number tht is the concept of linspace. 

# each of these numbers have 3.333 between them.

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [95]:
np.linspace(0,10, num=4).shape #gives a one-d array of 4 elements

(4,)

In [96]:
import datetime
datetime.datetime.now()

datetime.datetime(2024, 8, 25, 18, 7, 24, 143856)

# ARRAY ATTRIBUTES

1. shape
2. ndim
3. size #number of elements present
4. itemsize #capacity of each element in array
5. dtype #data type of an array

In [97]:
a1 = np.arange(10,dtype = np.int32)
a2 = np.arange(12, dtype = float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [98]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [99]:
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [100]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [102]:
a1.shape, a2.shape, a3.shape

((10,), (3, 4), (2, 2, 2))

In [104]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [105]:
a1.size #how many elements are present in arrayy

10

In [106]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [107]:
# bits - 0 or 1 ie. on or off denoted as 'b'

# bytes - is made up of 8 bites ie. 10010001 # 8 bits ka collection ko 1 byte bolte hai. denoted as 'B'

# 1 byte = 8 bits

# 32 bits would be 32/8 = 4 bytes


In [109]:
a1.itemsize #returns capacity of every element in an array in Bytes. 

# a1 is an array : array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# here each element in a1 like 0,1,2,3 -- har ek element kitna space le rhi hai computes ka that is 
# a1 ka dtype was np.int32 # which means 32 bits. ie. 32/8= 4 bytes .

# each element of a1 array is taking up 4 bytes of space

4

In [110]:
a1.dtype

dtype('int32')

In [ ]:
#array is homogenous stores elements of single type

In [111]:
a4 = np.array([1,2.5])
a4

array([1. , 2.5])

In [113]:
a4[0].dtype

dtype('float64')

In [115]:
a4[1].dtype

dtype('float64')

In [116]:
a5 = np.array([1, "python"])
a5

array(['1', 'python'], dtype='<U11')

In [117]:
a5[0].dtype, a5[1].dtype

(dtype('<U1'), dtype('<U6'))

# As type

changes the array from one datatype to another datatype

In [118]:
a1
#all the eleemnts inside this array is in the form of int32

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [119]:
a1.dtype

dtype('int32')

In [121]:
a1.astype(str)
#converting each element in this array in the form of string type

array(['0', '1', '2', '3', '4', '5', '6', '7', '8', '9'], dtype='<U11')

In [123]:
a1.astype(float) #changed in decimals

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [128]:
a1 = a1.astype(float) #saave the result

In [124]:
s = "mayank"
s.split('a')

['m', 'y', 'nk']

In [126]:
s #split save nhi hua

'mayank'

In [129]:
a1.astype(np.int32)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Array operations

#when working on array

1. indexing

In [130]:
a1 = np.arange(1,10)
a1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [135]:
len(a1)

9

In [134]:
#indexing

a1[0]

1

In [133]:
a1[8]

9

In [136]:
a1[0:4]

array([1, 2, 3, 4])

In [138]:
a2 
# negative:-4   -3  -2    -1
# indexing: 0   1   2     3

# array([[ 0.,  1.,  2.,  3.],      0   -3
#        [ 4.,  5.,  6.,  7.],      1   -2
#        [ 8.,  9., 10., 11.]])     2   -1




array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [140]:
a2.shape # 3 rows and 4 columns 

(3, 4)

In [142]:
a2[0:2] #gives first two rows

array([[0., 1., 2., 3.],
       [4., 5., 6., 7.]])

In [143]:
a2[0:2, 0:2] #first two rows and first two columsn

array([[0., 1.],
       [4., 5.]])

In [145]:
a2[0] #just first row

array([0., 1., 2., 3.])

In [147]:
a2[0][2] #one-d array se we are extracting element.

2.0

In [148]:
l1 = [[1,2,3], 4, 5]
l1

[[1, 2, 3], 4, 5]

In [149]:
l1[0]

[1, 2, 3]

In [150]:
l1[2]

5

In [151]:
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [157]:
a2[1][0:3]

array([4., 5., 6.])

In [161]:
a2[1][0:3][-1]

6.0

In [163]:
a1[-8] #one -d array

2

In [164]:
a1[-9:-6]

array([1, 2, 3])

In [165]:
a1[-6:-9]

array([], dtype=int32)

In [168]:
a1[-1:-6]

array([], dtype=int32)

In [169]:
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [171]:
a2[2] #2nd row

array([ 8.,  9., 10., 11.])

In [172]:
a2[-3]

array([0., 1., 2., 3.])

## Arithmetic operations:

1. Binary operators
2. conditional operators


+, - , *, / , //(floor division- gives integer quotient), %(modulus: gives remainder)

In [173]:
a1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [175]:
a1/10

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [176]:
a1*2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [177]:
a1 + 5

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14])

In [178]:
a1 -5

array([-4, -3, -2, -1,  0,  1,  2,  3,  4])

In [182]:
a_new = np.array((2,4))
a_new

array([2, 4])

In [183]:
a_new//4

array([0, 1], dtype=int32)

In [186]:
a_new3 = np.array((1,2))
a_new3

array([1, 2])

In [190]:
a_new3%2 # modulus 1/2 gives 1 as remainder
                   #2/2 gives 0 as remainder

array([1, 0], dtype=int32)

In [189]:
2//4

0

In [191]:
a6 = np.arange(1,6)
a6

array([1, 2, 3, 4, 5])

In [192]:
a6>3

array([False, False, False,  True,  True])

In [220]:
list1 = ['sd','ff', 'ajay']
list2 = ['sd','hhh', 'ajay']

In [198]:
list1==list2

False

In [207]:
for i in range(len(list1)):
    if list1[i] == list2[i]:
        print(True)

    else: 
        print(False)

True
False


In [215]:
[ list1[i]==list2[i] for i in range(len(list1))]

[True, False, True]

In [216]:
[True if list1[i] == list2[i] else 'kk' for i in range(len(list1)) ]

[True, 'kk', True]

In [221]:
a6>3

array([False, False, False,  True,  True])

In [222]:
a6!=3

array([ True,  True, False,  True,  True])

In [223]:
a6==3

array([False, False,  True, False, False])

In [224]:
a6

array([1, 2, 3, 4, 5])

In [225]:
#print all the numbers which are greater than 3 inside of the array

a6 > 3

array([False, False, False,  True,  True])

In [226]:
a6[a6 > 3]

array([4, 5])

In [227]:
a6[[True, False,False, False,False] ] #giving one array inside an array to know the exact elements inside that.

array([1])

In [228]:
a6 > 4

array([False, False, False, False,  True])

In [230]:
np.where(a6 > 3)

(array([3, 4], dtype=int64),)

In [233]:
a6

array([1, 2, 3, 4, 5])

In [235]:
np.where(a6> 3) #this one gives the inddexes

(array([3, 4], dtype=int64),)

In [236]:
a6

array([1, 2, 3, 4, 5])

In [237]:
a6 = a6*10
a6

array([10, 20, 30, 40, 50])

In [238]:
np.where(a6>30) #indexes and not values

(array([3, 4], dtype=int64),)

In [ ]:
# np.max
# np.min,
# np.prod
# np.mean
# np.sin
# np.divide
# np.cos

In [241]:
a1 = np.arange(0,4).reshape(2,2)
a1

array([[0, 1],
       [2, 3]])

In [242]:
np.max(a1)

3

In [ ]:
# 0 for column
# 1 for row

In [243]:
np.max(a1,axis = 1) #across rows what is the maximun

array([1, 3])

In [245]:
np.max(a1,axis = 0) #across columns kya maxium hai by column.

array([2, 3])

In [246]:
np.min(a1,axis=1)

array([0, 2])

In [247]:
np.min(a1,axis = 0) #column

array([0, 1])

In [249]:
np.prod(a1) #products of all elements

0

In [256]:
a1

array([[0, 1],
       [2, 3]])

In [257]:
np.mean(a1) #average

1.5

In [259]:
np.mean(a1,axis =1) #across rows. 

# 1+2 /2 =0.5
# 2+3 /2 = 2.5


array([0.5, 2.5])

In [260]:
np.sin(a1) #sin of each elementss

array([[0.        , 0.84147098],
       [0.90929743, 0.14112001]])

# iterate of an array
# how to access each and very element of an array
# np.ravel

In [262]:
l1 = [1,2,3]
l2 = [l1,l1,l1]
l3 = [l2,l2,l2]

In [266]:
l1 #oned list

[1, 2, 3]

In [265]:
l2 # 2 d list

[[1, 2, 3], [1, 2, 3], [1, 2, 3]]

In [268]:
l3 # 3d list

[[[1, 2, 3], [1, 2, 3], [1, 2, 3]],
 [[1, 2, 3], [1, 2, 3], [1, 2, 3]],
 [[1, 2, 3], [1, 2, 3], [1, 2, 3]]]

In [269]:
for element in l1:
    print(element)

1
2
3


In [271]:
for elem in l2:
    for nested  in elem:

          print(nested)

1
2
3
1
2
3
1
2
3


In [272]:
for one in l3:
    print(one)
    for second in one:
        print(second)

        for third in second:
            print(third)

[[1, 2, 3], [1, 2, 3], [1, 2, 3]]
[1, 2, 3]
1
2
3
[1, 2, 3]
1
2
3
[1, 2, 3]
1
2
3
[[1, 2, 3], [1, 2, 3], [1, 2, 3]]
[1, 2, 3]
1
2
3
[1, 2, 3]
1
2
3
[1, 2, 3]
1
2
3
[[1, 2, 3], [1, 2, 3], [1, 2, 3]]
[1, 2, 3]
1
2
3
[1, 2, 3]
1
2
3
[1, 2, 3]
1
2
3


In [273]:
a7 = np.arange(10,dtype = np.int32)
a8 = np.arange(12,dtype=float).reshape(3,4)
a9 = np.arange(8).reshape(2,2,2)

In [274]:
a7,a8,a9

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]]),
 array([[[0, 1],
         [2, 3]],
 
        [[4, 5],
         [6, 7]]]))

In [276]:
for i in a7:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [277]:
for i in a8:
    print(i)

[0. 1. 2. 3.]
[4. 5. 6. 7.]
[ 8.  9. 10. 11.]


In [278]:
for i in a9:
    print(i)

[[0 1]
 [2 3]]
[[4 5]
 [6 7]]


In [282]:
a9

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [283]:
np.ravel(a9)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [284]:
for i in np.ravel(a9):
    print(i)

0
1
2
3
4
5
6
7


In [286]:
a8

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [287]:
np.ravel(a8)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [288]:
for i in np.ravel(a8):
    print(i)

0.0
1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0
10.0
11.0


In [290]:
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
