# DONT COMPARE DOT MATRIX AND ARRAY MULTIPLICATION

# MATRIX OPERATIONS IN NUMPY

## Dot products: np.dot
## cos product
## Broadcasting




In [1]:
import numpy as np

In [3]:
a1 = np.arange(1,7).reshape(2,3) #2x3= 6 number of elements
a1

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
a2 = np.arange(7,13).reshape(3,2)
a2

array([[ 7,  8],
       [ 9, 10],
       [11, 12]])

In [7]:
np.dot(a1,a2) #this is a dot prodcut.

array([[ 58,  64],
       [139, 154]])

# Normal numpy array operation

1. is added element wise
2. is divided element wise
3. is subtracted element wise
4. is multiplied element wise

if addition,subtraction cant be done properly then broadcasting is done for the operations to happen.

In [8]:
a5 = np.arange(1,7).reshape(2,3)
a5

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
a6 = np.arange(11,17).reshape(2,3)
a6

array([[11, 12, 13],
       [14, 15, 16]])

In [11]:
a5 + a6 #added on respective locations

array([[12, 14, 16],
       [18, 20, 22]])

In [12]:
a5-a6

array([[-10, -10, -10],
       [-10, -10, -10]])

# BROADCASTING
# making a copy of specific rows and columsn so that error na aye
# should shape always be same to do the product of normal operation??
# if some operation is applied a row/column wise , it has to be done for all the column wise.

# numpy tries to not give errors. 
# only one row and one column can be broadcasted 


In [13]:
a5*a6 #get multiplied respective elements.

array([[11, 24, 39],
       [56, 75, 96]])

In [15]:
new_s = np.arange(1,10).reshape(3,3)
new_s # 3x3 matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
old = np.arange(1,4).reshape(3,1)
old # 3X1 matrix

array([[1],
       [2],
       [3]])

In [19]:
new_s + old 

array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12]])

In [20]:
new_s * old #each element is multiplying   #doing broadcasting so that multiplication ho jaye it is not a dot product 
# dont confuse it with dot product.

array([[ 1,  2,  3],
       [ 8, 10, 12],
       [21, 24, 27]])

# here in this example broadcasting wont happen as we cant do broadcasting across rows.

In [22]:
a11 = np.arange(1,11).reshape(5,2)
a11

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [24]:
a9 = np.arange(1,10).reshape(3,3)
a9

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
a9+a11

ValueError: operands could not be broadcast together with shapes (3,3) (5,2) 

In [26]:
s= "python"

In [27]:
s[100:1000:100]

''

In [31]:
array_1 = np.arange(1,4).reshape(1,3)
array_1

array([[1, 2, 3]])

In [32]:
array_2 = np.arange(1,4).reshape(3,1)
array_2

array([[1],
       [2],
       [3]])

In [33]:
array_1 * array_2 # * is not dot product but element wise multiplication will happen by broadcasting

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [34]:
b1 = np.array([1,2,3])
b1

array([1, 2, 3])

In [42]:
b1.shape #its a one -d array one dimensional 

(3,)

In [40]:
b2= b1.reshape(1,3) # one row and 3 columns
b2

array([[1, 2, 3]])

In [43]:
b2.shape #2-d array 2 dimensional basically

(1, 3)

In [44]:
b1.reshape(3,1)

array([[1],
       [2],
       [3]])

In [45]:
a12 = np.arange(0,9).reshape(3,3)
a12

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [46]:
a13 = np.arange(0,6).reshape(3,2)
a13

array([[0, 1],
       [2, 3],
       [4, 5]])

In [48]:
a12 + a13 #cant broadcast this

ValueError: operands could not be broadcast together with shapes (3,3) (3,2) 

In [49]:
a13 = np.arange(0,3).reshape(1,3)
a13

array([[0, 1, 2]])

In [50]:
a12 +a13

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])

In [57]:
# broadcasting: when we are adding a scalar to an array is also an example of broadcasting only

n_array = np.arange(1,11).reshape(5,2)
n_array

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [58]:
n_array *5

array([[ 5, 10],
       [15, 20],
       [25, 30],
       [35, 40],
       [45, 50]])

# examples of broadcasting


# Example 1: adding a scalar to an array

In [61]:
import numpy as np

arr = np.array([1,2,3])
scalar = 5
result = arr+scalar
print(arr)
print(scalar)
print(result)

[1 2 3]
5
[6 7 8]


# Example 2: Adding arrays with compatible shapes

In [64]:
arr1 = np.array([1,2,3]) #shape: (3,)
arr1


array([1, 2, 3])

In [63]:
arr2 = np.array([[4],[5],[6]])  #shape (3,1)
arr2

array([[4],
       [5],
       [6]])

In [69]:
np.array([[[3],[3],[0],[9]]])

array([[[3],
        [3],
        [0],
        [9]]])

In [65]:
result = arr1 +arr2
result

array([[5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

# example 3: multiplying arrays with compatible shapes

In [70]:
arr1 = np.array([   [1,2,3],[4,5,6]   ])
arr1 #shape: (2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [71]:
arr2 = np.array([10,20,30])
arr2 #shape: (3,) or 

array([10, 20, 30])

In [72]:
result = arr1* arr2
result

array([[ 10,  40,  90],
       [ 40, 100, 180]])

# example 4: multiplying arrays with incompatible shapes

In [73]:
arr1 = np.array([1,2,3]) 
arr1 #shape: (3,)

array([1, 2, 3])

In [74]:
arr2 = np.array( [ [1,2], [3,4], [5,6] ])
arr2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [75]:
try:
    result = arr1 + arr2
    print(result)

except ValueError as e:
    print(e)

operands could not be broadcast together with shapes (3,) (3,2) 


# example 5: broadcasting in higher dimensions

In [76]:
arr1 = np.ones((4,3,2)) # 4 3x2 matrices this is 3d
arr1 #shape (4,3,2)

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [77]:
arr2 = np.array([2,3])
arr2 # shape: 2x3

array([2, 3])

In [79]:
result = arr1 * arr2
result

array([[[2., 3.],
        [2., 3.],
        [2., 3.]],

       [[2., 3.],
        [2., 3.],
        [2., 3.]],

       [[2., 3.],
        [2., 3.],
        [2., 3.]],

       [[2., 3.],
        [2., 3.],
        [2., 3.]]])

# example 6: practical eg. - normalising rows of aa matrix

# common use of brooadcasting is in normalising the data.
# hence normalise the rows of a 2d array

In [80]:
matrix = np.array( [[1,2,3],[4,5,6],[7,8,9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [81]:
row_sums = matrix.sum(axis=1) #np.sum #summing accrowss rows
row_sums

array([ 6, 15, 24])

In [82]:
row_sums = row_sums.reshape(-1,1)
row_sums

array([[ 6],
       [15],
       [24]])

In [83]:
normalised_matrix = matrix/row_sums
normalised_matrix

array([[0.16666667, 0.33333333, 0.5       ],
       [0.26666667, 0.33333333, 0.4       ],
       [0.29166667, 0.33333333, 0.375     ]])

# example 7: boradcasting with different dimensions

In [84]:
arr1 = np.array( [ [1,2,3],[4,5,6],[7,8,9] ])
arr1 #shape: (3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [85]:
arr2 = np.array([1,0,1]) #shape: (3,)
arr2

array([1, 0, 1])

In [86]:
result = arr1 + arr2
result

array([[ 2,  2,  4],
       [ 5,  5,  7],
       [ 8,  8, 10]])