# DONT COMPARE DOT MATRIX AND ARRAY MULTIPLICATION

# MATRIX OPERATIONS IN NUMPY

## Dot products: np.dot
## cos product
## Broadcasting




In [1]:
import numpy as np

In [3]:
a1 = np.arange(1,7).reshape(2,3) #2x3= 6 number of elements
a1

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
a2 = np.arange(7,13).reshape(3,2)
a2

array([[ 7,  8],
       [ 9, 10],
       [11, 12]])

In [7]:
np.dot(a1,a2) #this is a dot prodcut.

array([[ 58,  64],
       [139, 154]])

# Normal numpy array operation

1. is added element wise
2. is divided element wise
3. is subtracted element wise
4. is multiplied element wise

if addition,subtraction cant be done properly then broadcasting is done for the operations to happen.

In [8]:
a5 = np.arange(1,7).reshape(2,3)
a5

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
a6 = np.arange(11,17).reshape(2,3)
a6

array([[11, 12, 13],
       [14, 15, 16]])

In [11]:
a5 + a6 #added on respective locations

array([[12, 14, 16],
       [18, 20, 22]])

In [12]:
a5-a6

array([[-10, -10, -10],
       [-10, -10, -10]])

# BROADCASTING
# making a copy of specific rows and columsn so that error na aye
# should shape always be same to do the product of normal operation??
# if some operation is applied a row/column wise , it has to be done for all the column wise.

# numpy tries to not give errors. 


In [13]:
a5*a6 #get multiplied respective elements.

array([[11, 24, 39],
       [56, 75, 96]])

In [15]:
new_s = np.arange(1,10).reshape(3,3)
new_s # 3x3 matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
old = np.arange(1,4).reshape(3,1)
old # 3X1 matrix

array([[1],
       [2],
       [3]])

In [19]:
new_s + old 

array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12]])

In [20]:
new_s * old #each element is multiplying   #doing broadcasting so that multiplication ho jaye it is not a dot product 
# dont confuse it with dot product.

array([[ 1,  2,  3],
       [ 8, 10, 12],
       [21, 24, 27]])

# here in this example broadcasting wont happen as we cant do broadcasting across rows.

In [22]:
a11 = np.arange(1,11).reshape(5,2)
a11

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [24]:
a9 = np.arange(1,10).reshape(3,3)
a9

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
a9+a11

ValueError: operands could not be broadcast together with shapes (3,3) (5,2) 

In [26]:
s= "python"

In [27]:
s[100:1000:100]

''

In [31]:
array_1 = np.arange(1,4).reshape(1,3)
array_1

array([[1, 2, 3]])

In [32]:
array_2 = np.arange(1,4).reshape(3,1)
array_2

array([[1],
       [2],
       [3]])

In [33]:
array_1 * array_2 # * is not dot product but element wise multiplication will happen by broadcasting

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [34]:
b1 = np.array([1,2,3])
b1

array([1, 2, 3])

In [42]:
b1.shape #its a one -d array one dimensional 

(3,)

In [40]:
b2= b1.reshape(1,3) # one row and 3 columns
b2

array([[1, 2, 3]])

In [43]:
b2.shape #2-d array 2 dimensional basically

(1, 3)