# MATRIX OPERATIONS IN NUMPY

## Dot products: np.dot
## cos product




In [1]:
import numpy as np

In [3]:
a1 = np.arange(1,7).reshape(2,3) #2x3= 6 number of elements
a1

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
a2 = np.arange(7,13).reshape(3,2)
a2

array([[ 7,  8],
       [ 9, 10],
       [11, 12]])

In [6]:
np.dot(a1,a2)

array([[ 58,  64],
       [139, 154]])