# MATRIX OPERATIONS IN NUMPY

## Dot products: np.dot
## cos product
## Broadcasting




In [1]:
import numpy as np

In [3]:
a1 = np.arange(1,7).reshape(2,3) #2x3= 6 number of elements
a1

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
a2 = np.arange(7,13).reshape(3,2)
a2

array([[ 7,  8],
       [ 9, 10],
       [11, 12]])

In [7]:
np.dot(a1,a2)

array([[ 58,  64],
       [139, 154]])

# Normal numpy array operation

In [8]:
a5 = np.arange(1,7).reshape(2,3)
a5

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
a6 = np.arange(11,17).reshape(2,3)
a6

array([[11, 12, 13],
       [14, 15, 16]])

In [11]:
a5 + a6 #added on respective locations

array([[12, 14, 16],
       [18, 20, 22]])

In [12]:
a5-a6

array([[-10, -10, -10],
       [-10, -10, -10]])

# BROADCASTING
# making a copu
# should shape always be same to do the product of normal operation??


In [13]:
a5*a6 #get multiplied respective elements.

array([[11, 24, 39],
       [56, 75, 96]])

In [15]:
new_s = np.arange(1,10).reshape(3,3)
new_s # 3x3 matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
old = np.arange(1,4).reshape(3,1)
old # 3X1 matrix

array([[1],
       [2],
       [3]])

In [19]:
new_s + old

array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12]])

In [20]:
new_s * old #each element is multiplying  

array([[ 1,  2,  3],
       [ 8, 10, 12],
       [21, 24, 27]])

In [22]:
a11 = np.arange(1,11).reshape(5,2)
a11

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [24]:
a9 = np.arange(1,10).reshape(3,3)
a9

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
a9+a11

ValueError: operands could not be broadcast together with shapes (3,3) (5,2) 

In [26]:
s= "python"

In [27]:
s[100:1000:100]

''

In [21]:
s= "python"