## Numpy: numerical python

# creates arrays and matrics.
# helps to do computation with n-dimensional arrays
# it has just one data structure 
# it has nd arrays [n-dimensional array]

In [5]:
import numpy as np

In [1]:
l1 = [1,2,3] #list

In [2]:
l1 = [[1,2,3]] #list is v slow and numpy array has c++ in background and are a lot faster.

## Arrays vs List

# Arrays are fixed size(immutable) - this means numpy arrays only
# needs to be created newly if anything needs to be changed. 
# homogenous
# good for mathematical functions(dot product, determinant.)

# Lists are mutable. Can be chnaged.
# heterogenous
# we dont have that here 

In [3]:
l1 = [1,2,3,4,"abc",1.5] # this list has 3 different data types ie. it is heterogenous in nature.

In [6]:
np.array((1,2,3)) #needs to be single type

array([1, 2, 3])

In [8]:
n1 =np.array((1,2,3.5))  #converts all to float
n1

array([1. , 2. , 3.5])

In [10]:
type(n1[2])

numpy.float64

In [11]:
n2 = np.array(('1','2','3'))
n2

array(['1', '2', '3'], dtype='<U1')

In [12]:
n2 = np.array(('1',2,3.5)) #makes everything as string so that datatype is same.
n2

array(['1', '2', '3.5'], dtype='<U32')

In [18]:
n3 = np.array([1,3,4])
n3

array([1, 3, 4])

# Creating numpy arrays

In [ ]:
np.array() #arrays are list of objects of same type, all interger , all float

## dimensions

# dimensions are something which telss you how mnay directions you can move into. 

# if in a space you have a single point/single number -- that number cant be moved left or right. ie. means it is a zero dimension. # 1 direction = 1 dimension.

# if a excel sheet can have in 2 directions. 

# on a single line you can move only in one direction.


In [ ]:
# 0 dimension - means zero direction

In [13]:
n0 = np.array(3) #array having a single point.  #providing it a scalar
n0

array(3)

In [15]:
n0.ndim #dimensions of array

0

In [19]:
n1 = np.array([1,2,3]) #single dimension #one dimensional has 3 points in it
n1


array([1, 2, 3])

In [20]:
n1.ndim

1

In [22]:
n2 = np.array([[1,2,3], [4,5,6]]


               ) # 2-dimensional arrays # 2-d is a plane
n2,n2.ndim

(array([[1, 2, 3],
        [4, 5, 6]]),
 2)

In [30]:
n3 = np.array(
  [
  [[1,2,3] ,  [4,5,6]],   # these are 2 - 2d arrays  / basically 2 planes.
  [[7,8,9] , [9,29,34]]
 
  ]

) # 3 -d arrays you are just essentially moving a plane so its basically multiple 2-d arrays./plane
n3,n3.ndim

(array([[[ 1,  2,  3],
         [ 4,  5,  6]],
 
        [[ 7,  8,  9],
         [ 9, 29, 34]]]),
 3)

In [31]:
n3.shape # 2 (2*3) arrays hai

(2, 2, 3)

In [33]:
n4 = np.array([n3,n3]) # 2 n3 arrays should give you n4 array

n4, n4.ndim

(array([[[[ 1,  2,  3],
          [ 4,  5,  6]],
 
         [[ 7,  8,  9],
          [ 9, 29, 34]]],
 
 
        [[[ 1,  2,  3],
          [ 4,  5,  6]],
 
         [[ 7,  8,  9],
          [ 9, 29, 34]]]]),
 4)

In [ ]:
#np.array can be created using type and without type